collectiveaccess/pawtucket2

app/controllers/DetailController.php
* The plain text emails work and are customisable while the html emails
don't render
=> Fix html email share template path

themes/default/views/Browse/browse_results_images_html.php
Set $vs_label_detail_link to {$vs_table}.preferred_labels, rather than {$vs_table}.preferred_labels.name. Previously, an entity name would not display in image browse mode, because an entity has a displayname rather than a name.
=> Display title on Entity image browse

themes/default/assets/pawtucket/css/main.css
Fix two typos that won't let css to validate correctly.
=> Fix breaking css typos in main stylesheet

app/lib/Media/MediaViewers/VideoJS.php
I noticed that captions are not being set in the $pa_options sent to Video.php when using the VideoJS media viewer.  This change adds them in a way similar to how TileViewer does it, so that VTT and SRT caption files are correctly displayed by video.js.
=> Set video captions when using VideoJS media viewer

assets/jquery/jquery-tileviewer/jquery.tileviewer.js
All other parts of this system use a parabolic coefficient when calculating the relative position.  It was missing here and simply needed to be added.
=> Fix Image Overview Panning

app/controllers/LoginRegController.php
Strip tags to sanitize input in User profile and in Tags & Comments.
I had a mail from etat.ge.ch audit firm that reports these as XSS injection risk in their automated exam.
=> Strip tags to sanitize input in User profile

app/controllers/DetailController.php
Strip tags to sanitize input in User profile and in Tags & Comments.
I had a mail from Etat.ge.ch audit firm that reports this as XSS injection risk in their automated tool.
=> sanitize input in Tags & Comments

themes/default/views/bundles/representation_viewer_html.php
jcarousel's `last` method does NOT return the "current" item, and this screws up the entire thumbnail system.  Substituting the `target` method resolves the problems.
Fixes #38
=> Corrected Carousel Init

app/helpers/displayHelpers.php
Fixes #53 
When `caRepresentationViewer()` checks for a `rank` value, it is incorrectly seeking a representation x representation relationship.  The subject argument needs to be used instead of the representation search result.
=> Slide Sort Querying Wrong Table

app/lib/Parsers/DisplayTemplateParser.php
limit was set to the options array without been previously set, then some value negociation without setting afterwards, so I think it might be better to hold setting in the options array till after the negocation of its value?
=> set limit in options

app/lib/BaseFindEngine.php
we had an edge case while performing an advanced objects search with a custom sort on related entity labels ie:
sortBy = {
Entity = ca_entity_labels.surname;ca_entity_labels.forename,
...
This sorting resulted in zero results in some cases (where none of the objects had entities).
Sorts are handled by INNER joining all the related tables, effectively causing the resultset to be filtered before it can be sorted when there were no related tables. Entities are not required, making it hard to get this default filtering always matching reality.
It seems appropriate to do LEFT joins instead, and (force) inner joins only on the 'selecting' joins (hit_table), so that the final resultset is complete for the objects, with empty information for the related tables (in our case entities, …
=> apply sort, without accidental filtering

app/lib/Auth/Adapters/Shibboleth.php
Currently there is a chicken and egg situation with the Shibboleth (SAML) authentication adapter. The ca_users::authenticate() method calls the AuthenticationManager::authenticate() which then calls Shibboleth::authenticate()  which will always fail because the adapter (shibboleth) says it supports (__CA_AUTH_ADAPTER_FEATURE_AUTOCREATE_USERS__ = true) auto creating users but then in the authenticate method it does a check to see whether the user exists in the CA database.
ca_users then goes on to say ok what's the username for the user from SAML and tries to get more user information for a username which it doesn't have because the user has not been authenticated.
This commit fixes that issue.
=> NOJIRA Support user creation in Shibboleth authentication adapter

app/helpers/browseHelpers.php
[This small change prevent having double slash '//' in URL which is replaced
by a single slash '/' later in routing and resulting missing view error.
The error is described here:
https://collectiveaccess.org/support/index.php?p=/discussion/299474/browse-view
URL as missing key where only single slash is visible.
=> Prevent having double slash '//' in URL

app/lib/BaseFindEngine.php
This fixes sorting by attributes which data type do not use `value_sortable` field for sorting.
This includes attribute of type currency, file size, floor plan, geocode, integer, length, time code, weight, and also date range in older versions of Providence.
A simple way to reproduce the bug this PR solves is to try to browse objects sorted by price. Using the default installation profile, each object has a `purchase_price` attribute, so you can add a "sort by price" sort in `browse.conf`:
```
browseTypes = {
objects = {
sortBy = {
Price = ca_objects.purchase_price,
},
},
}
```
You will see that Pawtucket fails to sort correctly in that case. It also fails to sort similar attributes from related tables.
=> Fix sorting by certain attributes

themes/default/assets/pawtucket/css/main.css
On the object detail view, when there are more than two images, trying to display images in any non-sequential order will trigger a display bug. For example, after page load, the first image is displayed, then, clicking on the third image will display it, but then, clicking on the second image won’t do anything.
My analysis:
Jcarousel displays images concatenated as inline elements and horizonrally scrolls around to display the selected image. However, in some situations, an image has a zero-height and does not take any space, resulting in misalignment of horizontal scroll position (and JS code somewhat failing). CSS `min-height` ensures images will always take their allocated width.
This bug is currently visible on [this page](https://comediassueltasusa.org/collection/Detail/objects/12679 …
=> Fix thumbnail display in representation viewer

app/helpers/themeHelpers.php
Legacy signature (deprecated as of PHP 7.4.0, removed as of PHP 8.0.0):
`implode(array $array, string $separator): string`
https://www.php.net/manual/en/function.implode.php
=> php8 signature for implode function

app/models/ca_site_pages.php, app/version.php
Updating the model and schema version
=> Bring in line with change on providence

app/conf/media_display.conf, app/helpers/displayHelpers.php
Currently the icons used in the representation toolbar (overlay view, download, compare) are hardcoded into the displayHelpers.php.  This enables the icons to be set in the media_display.conf and used inside the function in displayHelpers.php.
=> Ability to edit the icons used in rep toolbar

assets/jquery/jquery-tileviewer/jquery.tileviewer.js
All other parts of this system use a parabolic coefficient when calculating the relative position. It was missing here and simply needed to be added.
=> Include #39 in master

themes/default/views/bundles/representation_viewer_html.php
Fixes #85 
For reasons I don't fully understand, the jCarousel was broken when the last thumbnail was clicked first and the aspect of the first media was taller than the last media.
This workaround fixes the problem by:
- Forcing the 2nd-to-last media to always load before the last media.
- Using the `scroll` event instead of `scrollend` to minimize race conditions.
=> Force display of media when last thumbnail clicked first.

app/lib/Service/IIIFService.php
Arbitrary value of 1 hour allows web browsers to close and re-open overlay viewers without requesting image tiles every time.  
Complements https://github.com/collectiveaccess/providence/pull/1612
=> Enabled client-side caching in the IIIF service.

app/helpers/displayHelpers.php
Fixes #115
By calling `getRepresentationRelationshipTableName` with a representation, the script was looking for a representation x representation relationship.  This is wrong.  The related object needs to be passed instead.
=> Fixed wrong table reference

themes/default/views/bundles/representation_viewer_html.php
Fixes #127 
The previous implementation assumed slides could be indexed using the thumbnail sequence, which does not work because thumbnails and slides are not in the same order unless the primary representation happens to be first.
This PR refactors the function `setItem` to assume the input is a thumbnail sequence number, **not** the slide array index and **not** the representation ID.  This function grabs the thumbnail's representation ID and scans the slide list to find the corresponding slide index.
Added function `setByIndex` which assumes the input is the targeted slide array index.  This function extracts the representation ID from the slide list and uses it to find the element ID of a corresponding thumbnail.
=> Refactored Rep Thumbnail Clicks
